### ISSUE TITLE
M5StickC not turning on

### ISSUE THREAD

**Issue by OniiKuma** [m5stack/M5StickC#159]
### Describe the bug

So I just got into this IOT class and we were given M5StickC's to work with for the remainder of this class. I messed around with the led light using the blink example in Arduino IDE but I couldn't get it to stop. I had the normal human urge to turn it off so I did. However, when I power it on now, the light still keeps blinking but the screen doesn't turn on anymore. Can someone please help me with this issue? I would hate it if I have to return to class with a malfunctioning device I literally jus got. 

### To reproduce

1. Plug the M5StickC in
2. Install the esp32 board manager
3. Use the blink example in Arduino IDE 
4. Unplug the M5StickC
5. Power it off

### Expected behavior

After this happens, it should power off but when you turn it back on, the blink function still runs and the screen doesn't turn on.

### Environment

- OS:
- IDE &IDE Version:
- Repository Version:

### Issue checklist

- [X] I searched for previous reports in [the issue tracker](https://github.com/m5stack/M5StickC/issues?q=)
- [X] My report contains all necessary details

**Comment by Tinyu-Zhao** [comment]
The Blink example is provided by ESP32, as you can see in the picture below LED_BUILTIN is defined to a pre-defined pin, but we don't have this definition in the preset file (I'm not sure if this will damage the hardware)

<img width="1010" alt="image" src="https://user-images.githubusercontent.com/44396641/215382879-d73c61bf-63cd-4b95-8f7c-616f1e48f367.png">

You could try changing the LED_BUILTIN to 10 in the example, it would be safer to do so

The screen does not light up because you have not written anything in the program to drive the screen, you can try to use this [program](https://github.com/m5stack/M5StickC/blob/master/examples/Basics/Display/Display.ino) to light up the screen
